### ISSUE TITLE
Get device information

### ISSUE THREAD

**Issue by jonasBoss** [FreeSpacenav/libspnav#11]
I would like to request functions which provide access to device specific information. Such as number of buttons, number of axes and range of axes.

**Comment by jtsiomb** [comment]
Yeap, that's in the todo for some time now. It will require a new incompatible communication protocol though, and therefore can only work if the client program uses the UNIX domain socket interface, not the X11 one.

I've put this off for long, but I need to get on with designing this new protocol, and finding a way to gracefully fall back to the old one if not supported. I'll take some thinking through.

**Comment by jtsiomb** [comment]
Status update: I started working on this issue. Came up with a new protocol for spacenavd which will work transparently with old clients, while adding a lot of functionality and device queries for new clients. Should be completed and usable within the next couple of weeks.

**Comment by jtsiomb** [comment]
The current libspnav code (git head) is now capable of retrieving device information from spacenavd. None of this is in an official release yet on either side (spacenavd/libspnav), and there might be some minor changes and fixes before the official release, but I don't expect the new API entry points to change.
