### ISSUE TITLE
Missing pkgconfig 

### ISSUE THREAD

**Issue by albfan** [FreeSpacenav/libspnav#14]
Now libspav is used on GUI it would be great to have pkgconfig files.

I was able to add with meson buildsystem and works, just have no idea how make does that. Something like https://people.freedesktop.org/~dbn/pkg-config-guide.html

**Comment by jtsiomb** [comment]
Adding a pkgconfig file is extremely easy. It doesn't need build system support. I never did that because I don't think it's necessary for a library which can be linked simply by `-lspnav` and doesn't require anything extra to be passed to the compiler or linker. Do you have a use-case where having a pkgconfig file is useful?

**Comment by albfan** [comment]
Of course it don't new buildsystem. I mean as an example.

is just, hey buildsystem I need dependency, do all needed to use it.

https://github.com/albfan/spnavcfg/blob/meson/src/meson.build#L7

but even on meson you can add that global config `-lsnapv`

My use case is: to work on a OS integration, be able to add a tester like cube example on gnome-control-center or similar.

This issue is mostly about, if we use libspnav, why pkg-config is not provided? This issue can be the discussionn about that.

I'm totally fine if libspnav does not provide it, as you mention is easy to link this library.

**Comment by eli-schwartz** [comment]
pkg-config files allow installing to user-specified `./configure --prefix` and still finding the correct way to link to it (adding -I${includedir} and -L${libdir} to the interface cflags/libs of the pkg-config file). It also lets you associate a version number to the dependency, and thereby allows third-party consumers to require a specific minimum version as `pkg-config --cflags --libs "libspnav >= 0.x"`.

> doesn't require anything extra to be passed to the compiler or linker

This is only really true when the default prefix is used, hence the library and header are on the default compiler search path.

**Comment by jtsiomb** [comment]
Good point. I will put adding a pkg-config file in the todo list then.
