### ISSUE TITLE
Does libspnav support Qt6 ?

### ISSUE THREAD

**Issue by luzpaz** [FreeSpacenav/libspnav#17]
downstream discussion in FreeCAD repo: https://github.com/FreeCAD/FreeCAD/pull/7647?notification_referrer_id=NT_kwDOAD8s17I0Njg0MDQxMjg5OjQxNDAyNDc&notifications_query=is%3Aunread#discussion_r1008813889

**Comment by jtsiomb** [comment]
I can't imagine what in Qt6 would require explicit support by libspnav.

Anyone wishing to use libspnav in a Qt program, would have to take care to integrate libspnav input into the Qt event loop. There is an example of that in spnavcfg (which uses Qt5). I expect the integration to be similar if not identical with Qt6, but in any case it's up to the Qt program to do that integration, libspnav is GUI-agnostic and uses standard UNIX IPC mechanisms which should be usable with any GUI toolkit.

Until there is a report of something wrong with libspanv which stops Qt6 programs from using it, I'm closing this issue. Feel free to continue the discussion if something more concrete shows up.
