### ISSUE TITLE
Missing -lm link

### ISSUE THREAD

**Issue by XDjackieXD** [FreeSpacenav/libspnav#20]
After building, libspnav is not linked against lib math, resulting in some undefined symbols:
```
❯ ldd -d /usr/lib/libspnav.so.0.3
	linux-vdso.so.1 (0x00007ffdf9b1f000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f9d58970000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f9d58786000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f9d5875b000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007f9d58b0d000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f9d58756000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f9d5874e000)
undefined symbol: sincos	(/tmp/libspnav.so.0.3)
undefined symbol: sqrt	(/tmp/libspnav.so.0.3)
```
Adding `-lm` to the Makefile fixes this (and makes some software linking against libspnav compile/link without errors).

This is libspnav 1.1 as shipped with Archlinux (https://archlinux.org/packages/extra/x86_64/libspnav/)

**Comment by jtsiomb** [comment]
Thanks for pointing it out. fixed.

**Comment by djkato** [comment]
Hello @jtsiomb , I'm getting this issue with the latest libspnav on arch, while trying to build [dpentz/navjoy](https://github.com/dpentz/navjoy)
```
djkato@djkato§ ~/A/n/b/src (master)> ldd -d /usr/lib/libspnav.so.0.3
	linux-vdso.so.1 (0x00007978cdf1d000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x00007978cdd9c000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007978cdbab000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007978cdb80000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007978cdf1f000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007978cdb7b000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007978cdb73000)
undefined symbol: sincos	(/usr/lib/libspnav.so.0.3)
undefined symbol: sqrt	(/usr/lib/libspnav.so.0.3)
djkato@djkato ~/A/n/b/src (master)> pacman -Q libspnav spacenavd
libspnav 1.1-2
spacenavd 1.3-1
```

**Comment by jtsiomb** [comment]
I don't know what libspnav 1.1-2 is, but libspnav 1.1 does not have the fix. It was after 1.1 was released. Very little have happened between 1.1 and now in libspnav, but there are a couple of minor bugfixes, which might be enough to justify a new minor version bump. Until then, get the source from git.

**Comment by djkato** [comment]
> I don't know what libspnav 1.1-2 is

Probably an AUR version then. I did try to build it from git and replace the installed one, the issue went away. Seems it's already fixed, sorry for the ping.
