### ISSUE TITLE
spnav_open() always returns 0

### ISSUE THREAD

**Issue by tkelestemur** [FreeSpacenav/libspnav#3]
No matter if the SpaceNavigator is connected or not, the `spnav_open()` function always returns 0. It should return -1 when it's connected, right?

I'm on Ubuntu 16.04.

**Comment by jtsiomb** [comment]
Are you using the latest version of libspnav? The first thing `spnav_open` does is check if it's already connected and return -1 if so.

Edit: oh I'm sorry, are you talking about the device itself being present? No, that doesn't have anything to do with spnav connecting to spacenavd. You can connect without a device plugged, and will start receiving events when the device becomes available.

Being able to query the daemon about the device it's talking to, like if it's actually there, which one is it, and how many buttons it has, is a feature high in my list of things to do before releasing the next version.

**Comment by jtsiomb** [comment]
I'm closing this issue, since this is not really a bug. If you care about the protocol extensions for querying device properties, please open a feature request for that.
