### ISSUE TITLE
Using multiple SpaceMouse on one device

### ISSUE THREAD

**Issue by tobiascz** [FreeSpacenav/libspnav#9]
Hi,

I was hoping to use two spacemouses on a single system. The plan was to integrate it with ROS.
However i think there is an issue regarding the libspnav that it can only interface one device at a time: 
https://github.com/ros-drivers/joystick_drivers/issues/16

Are there any workarounds to this otherwise I have to run a second system just for the second spacemouse.

Cheers

**Comment by jtsiomb** [comment]
No, at the moment there's no way to do that. But it's a commonly requested feature, so I'll take it into account for the upcoming protocol redesign, whenever that happens.

**Comment by tobiascz** [comment]
Thanks for the clarification.
